file_format: "1"
id: keyball44
name: KEYBALL44
type: shield
url: https://github.com/Yowkees/keyball/tree/main
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - keyball44_left
  - keyball44_right
