manifest:
  remotes:
    - name: pmw33xx
      url-base: https://github.com/Luberry
  projects:
    - name: zmk
       remote: zmk
       revision: pmw3389
       import: app/west.yml
  self:
    path: config
