manifest:
  remotes:
    - name: pmw33xx
      url-base: https://github.com/yoshikik1991/zmk
  projects:
    - name: zmk
       remote: pmw33xx
       revision: pmw3389
       import: app/west.yml
  self:
    path: config
