 manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/Broeserl
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: playglound
      import: app/west.yml
  self:
    path: config
